### ISSUE TITLE
add linux support

### ISSUE THREAD

**Issue by boombuler** [boombuler/hid#1]
Don't have a working linux right now so it would be great if someone could provide some code :)

**Comment by nitram509** [comment]
Hi @boombuler 

I've started to implement the Linux port.
I've decided to go for libusb instead of hidraw, because of their broader adoption.
Enumeration() and Open() already works.
Write,Read and Close are in progress.

I also have to admit, that this is my _first_ lib in Go and my second Go program overall ;-)
So I really appreciate any feedback.

Details:
https://github.com/nitram509/hid

Regards
Martin

**Comment by boombuler** [comment]
Sounds great :+1: 

I will have a look!

**Comment by boombuler** [comment]
https://github.com/nitram509/hid/blob/master/hid_linux.go#L83 could be a problem, if you have multiple devices that have the same PID/VID... So it needs to call `libusb_open` istead of `libusb_open_device_with_vid_pid`

Do you have any idea what can be used as path? Looks like `libusb_get_port_numbers` in combination with PID/VID is the only possibility to identify unique devices.

To get the manifacturer you can use `libusb_get_string_descriptor` with iManufacturer from the device info.

**Comment by nitram509** [comment]
Thanks for your suggestions.
That are good improvements to the current code.
I will code on ;-)

**Comment by nitram509** [comment]
@boombuler I'm taking progress :-)

Thanks to your hints, we now have a possible candidate for 'Path'. (see getPath())
e.g. "1234:4711:03.01"   (productId:vendorId:port1..7)
What do you think?

What still missing:
- Write()
- ByPath() and Open() should use Path to open the correct devices

What is intended difference between Write() and WriteFeature()?

**Comment by boombuler** [comment]
Hi,
I didn't have a look at the code but the path looks good :) (At least if you keep in mind that the ports may have more parts if connected via a switch)

ByPath is easy if you have a stable path. Just look at the OSX implementation. That is the most easy way to do it, if the native lib doesnt support any better.

For `libusb_open` you can use the device you got from the iterating over all devices. which could be stored within the device info. 

`Write` should write an "output report" while `WriteFeature` should write a "feature report"
You may have a look at the osx source in this case too. since it is very close to what you have with libusb.
