### ISSUE TITLE
Proposed method "FindDevicesByProduct"

### ISSUE THREAD

**Issue by mapaiva** [boombuler/hid#6]
Hi, first of all congratulations for the project.

I'm using it right now and I miss a method to search devices by product (string). In my opinion, it will be great for the API have such facilitator method.

If you agree, I can personality take care of this :smile:

**Comment by boombuler** [comment]
I didn't need it yet but if you can provide some code I'll be happy to merge it (Though I'm not 100% sure that all three OS will provide the same strings.)

Thanks for the feedback.

**Comment by mapaiva** [comment]
PR created #7

**Comment by boombuler** [comment]
Merged ;)
